#!/bin/env ruby

SOURCE_FOLDER = __dir__


puts "running script in #{SOURCE_FOLDER}"
puts "to link the JS files to the destination folder: ./public/"

puts `rm -v ./public/index_halogen.js`
puts `ln -sv #{SOURCE_FOLDER}/vendor/purescript/halogen/counter/prod/index.js  ./public/index_halogen.js`

puts `rm -v ./public/index_flame.js`
puts `ln -sv #{SOURCE_FOLDER}/vendor/purescript/flame/counter/prod/index.js ./public/index_flame.js`
