#!/bin/env ruby

SOURCE_FOLDER = __dir__


puts "running script in #{SOURCE_FOLDER}"
puts "to link the JS files to the destination folder: ./public/"
puts ''

puts "removing cocktails"
`rm -v ./public/halogen-cocktail.js`
puts "copying cocktails"
`ln -sv #{SOURCE_FOLDER}/vendor/purescript/cocktails/prod/index.js  ./public/halogen-cocktail.js`

if File.exist? "./public/halogen-cocktail.js"
  puts "success"
else
  puts "missing"
end

puts "\n"


puts "removing halogen"
`rm -v ./public/index_halogen.js`
puts "copying halogen"
`ln -sv #{SOURCE_FOLDER}/vendor/purescript/halogen/counter/prod/index.js  ./public/index_halogen.js`

if File.exist? "./public/index_halogen.js"
  puts "success"
else
  puts "missing"
end

puts "\n"

puts "removing flame"
`rm -v ./public/index_flame.js`
puts "copying flame"
`ln -sv #{SOURCE_FOLDER}/vendor/purescript/flame/counter/prod/index.js ./public/index_flame.js`

if File.exist? "./public/index_flame.js"
  puts "success"
else
  puts "missing"
end

puts 'removing rescript'

`rm -v ./public/index_rescript.*`

ASSETS_FOLDER = "#{SOURCE_FOLDER}/vendor/rescript/my-rectript-experiment/dist/assets/"
dir = Dir.open ASSETS_FOLDER
dir.children.each do |c|
  if c.to_s.end_with? '.js'
    `ln -sv #{ASSETS_FOLDER}/#{c} ./public/index_rescript.js`
  end

  if c.to_s.end_with? '.css'
    `ln -sv #{ASSETS_FOLDER}/#{c} ./public/index_rescript.css`
  end
end
