#!/bin/env ruby

SOURCE_FOLDER = __dir__

def link_purescript(fname)
  puts "removing #{fname}"
  `rm -v ./#{fname}`
  puts "copying #{fname}"
  `ln -sv #{SOURCE_FOLDER}/vendor/purescript/cocktails/prod/index.js  ./#{fname}`

  if File.exist? "./#{fname}"
    puts "success"
  else
    puts "missing"
  end
  puts "\n"
end

puts "running script in #{SOURCE_FOLDER}"
puts "to link the JS files to the destination folder: ./public/"
puts ''


fname = 'public/flame-cocktail.js'
link_purescript fname

fname = 'public/halogen-cocktail.js'
link_purescript fname

fname = 'public/index_halogen.js'
link_purescript fname

fname = "public/index_flame.js"
link_purescript fname


puts 'removing rescript'

`rm -v ./public/index_rescript.*`

ASSETS_FOLDER = "#{SOURCE_FOLDER}/vendor/rescript/my-rectript-experiment/dist/assets/"
dir = Dir.open ASSETS_FOLDER
dir.children.each do |c|
  if c.to_s.end_with? '.js'
    `ln -sv #{ASSETS_FOLDER}/#{c} ./public/index_rescript.js`
  end

  if c.to_s.end_with? '.css'
    `ln -sv #{ASSETS_FOLDER}/#{c} ./public/index_rescript.css`
  end
end
